### PR TITLE
Fixed reported bugs

### PR DESCRIPTION
**Pull request by rezaiyan**
#49 #83 #115 #114

### CODE REVIEW

**Comment by helloseyedjafari** [comment]
#49 is not fixed.
but we are going to keep the changes in the layout

**Comment by helloseyedjafari** [comment]
regarding #114 . I can confirm the issue is fixed but, using layouts/viewGroups in ConstraintLayout is not a good practice and it's better to be avoided.
the new layout could be done exactly the same using just views without any parents (flat heriarichy)

Again no need to change here now
we will revisit it later if we see a bottle neck

**Review by helloseyedjafari — APPROVED** [review]
Thank you so much
you actually fixed them

**Comment by rezaiyan** [comment]
> #49 is not fixed.
> but we are going to keep the changes in the layout

I thought the second title should align (left) with the second dot!

**Pull request merged**
